### ISSUE TITLE
Reference errors when using multiple token sets

### ISSUE THREAD

**Issue by mark-nicepants** [aloisdeniel/style-dictionary-figma-flutter#2]
I'm trying to generate my Flutter assets using your library and the token set my designer gave me has 2 sets of data. It seems that that is currently not supported? I'm getting a lot of "Reference doesn't exist" on the second token set.

<details>
  <summary>Input tokens.json</summary>
  
  ```json
{
  "source": {
    "0": {
      "value": "0",
      "type": "letterSpacing"
    },
    "brand": {
      "50": {
        "value": "#f0faff",
        "type": "color"
      },
      "100": {
        "value": "#e0f5fe",
        "type": "color"
      },
      "200": {
        "value": "#bae8fd",
        "type": "color"
      },
      "300": {
        "value": "#7dd5fc",
        "type": "color"
      },
      "400": {
        "value": "#38bcf8",
        "type": "color"
      },
      "500": {
        "value": "#0ea5e9",
        "type": "color"
      },
      "600": {
        "value": "#028ac7",
        "type": "color"
      },
      "700": {
        "value": "#0370a1",
        "type": "color"
      },
      "800": {
        "value": "#075e85",
        "type": "color"
      },
      "900": {
        "value": "#0c506e",
        "type": "color"
      }
    },
    "gray": {
      "50": {
        "value": "#f9fafb",
        "type": "color"
      },
      "100": {
        "value": "#f3f4f6",
        "type": "color"
      },
      "200": {
        "value": "#e5e7eb",
        "type": "color"
      },
      "300": {
        "value": "#d1d5db",
        "type": "color"
      },
      "400": {
        "value": "#9ca3af",
        "type": "color"
      },
      "500": {
        "value": "#6b7280",
        "type": "color"
      },
      "600": {
        "value": "#4b5563",
        "type": "color"
      },
      "700": {
        "value": "#374151",
        "type": "color"
      },
      "800": {
        "value": "#1f2937",
        "type": "color"
      },
      "900": {
        "value": "#111827",
        "type": "color"
      }
    },
    "red": {
      "50": {
        "value": "#fef2f2",
        "type": "color"
      },
      "100": {
        "value": "#fee2e2",
        "type": "color"
      },
      "200": {
        "value": "#fecaca",
        "type": "color"
      },
      "300": {
        "value": "#fca5a5",
        "type": "color"
      },
      "400": {
        "value": "#f87171",
        "type": "color"
      },
      "500": {
        "value": "#ef4444",
        "type": "color"
      },
      "600": {
        "value": "#dc2626",
        "type": "color"
      },
      "700": {
        "value": "#b91c1c",
        "type": "color"
      },
      "800": {
        "value": "#991b1b",
        "type": "color"
      },
      "900": {
        "value": "#7f1d1d",
        "type": "color"
      }
    },
    "yellow": {
      "50": {
        "value": "#fefce8",
        "type": "color"
      },
      "100": {
        "value": "#fef9c3",
        "type": "color"
      },
      "200": {
        "value": "#fef08a",
        "type": "color"
      },
      "300": {
        "value": "#fde047",
        "type": "color"
      },
      "400": {
        "value": "#facc15",
        "type": "color"
      },
      "500": {
        "value": "#eab308",
        "type": "color"
      },
      "600": {
        "value": "#ca8a04",
        "type": "color"
      },
      "700": {
        "value": "#a16207",
        "type": "color"
      },
      "800": {
        "value": "#854d0e",
        "type": "color"
      },
      "900": {
        "value": "#713f12",
        "type": "color"
      }
    },
    "green": {
      "50": {
        "value": "#f0fdf4",
        "type": "color"
      },
      "100": {
        "value": "#dcfce7",
        "type": "color"
      },
      "200": {
        "value": "#bbf7d0",
        "type": "color"
      },
      "300": {
        "value": "#86efac",
        "type": "color"
      },
      "400": {
        "value": "#4ade80",
        "type": "color"
      },
      "500": {
        "value": "#22c55e",
        "type": "color"
      },
      "600": {
        "value": "#16a34a",
        "type": "color"
      },
      "700": {
        "value": "#15803d",
        "type": "color"
      },
      "800": {
        "value": "#166534",
        "type": "color"
      },
      "900": {
        "value": "#14532d",
        "type": "color"
      }
    },
    "white": {
      "value": "#ffffff",
      "type": "color"
    },
    "black": {
      "value": "#000000",
      "type": "color"
    },
    "transparent": {
      "value": "rgba(255,255,255,0)",
      "type": "color"
    },
    "General Sans": {
      "value": "General Sans",
      "type": "fontFamilies"
    },
    "Default": {
      "value": "140%",
      "type": "lineHeights"
    },
    "Footnote": {
      "value": "13",
      "type": "fontSizes"
    },
    "Subheadline": {
      "value": "15",
      "type": "fontSizes"
    },
    "Body": {
      "value": "17",
      "type": "fontSizes"
    },
    "Title": {
      "value": "20",
      "type": "fontSizes"
    },
    "LargeTitle": {
      "value": "34",
      "type": "fontSizes"
    },
    "Regular": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "Medium": {
      "value": "Medium",
      "type": "fontWeights"
    },
    "Bold": {
      "value": "Bold",
      "type": "fontWeights"
    }
  },
  "semantic": {
    "button": {
      "background": {
        "primary": {
          "default": {
            "value": "{brand.500}",
            "type": "color"
          },
          "pressed": {
            "value": "{brand.600}",
            "type": "color"
          }
        },
        "secondary": {
          "default": {
            "value": "{gray.800}",
            "type": "color"
          },
          "pressed": {
            "value": "{gray.900}",
            "type": "color"
          }
        },
        "disabled": {
          "default": {
            "value": "{gray.100}",
            "type": "color"
          }
        },
        "success": {
          "default": {
            "value": "{green.500}",
            "type": "color"
          },
          "pressed": {
            "value": "{green.600}",
            "type": "color"
          }
        },
        "destructive": {
          "default": {
            "value": "{red.500}",
            "type": "color"
          },
          "pressed": {
            "value": "{red.600}",
            "type": "color"
          }
        },
        "transparent": {
          "default": {
            "value": "{transparent}",
            "type": "color"
          }
        }
      },
      "foreground": {
        "default": {
          "value": "{white}",
          "type": "color"
        },
        "disabled": {
          "value": "{gray.200}",
          "type": "color"
        },
        "success": {
          "value": "{green.500}",
          "type": "color"
        },
        "destructive": {
          "value": "{red.500}",
          "type": "color"
        },
        "onTransparent": {
          "default": {
            "value": "{gray.900}",
            "type": "color"
          },
          "pressed": {
            "value": "{gray.800}",
            "type": "color"
          }
        }
      }
    },
    "background": {
      "default": {
        "value": "{gray.100}",
        "type": "color"
      },
      "neutral": {
        "value": "{white}",
        "type": "color"
      }
    },
    "default": {
      "footnote": {
        "regular": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Regular}",
            "lineHeight": "{Default}",
            "fontSize": "{Footnote}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "medium": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Medium}",
            "lineHeight": "{Default}",
            "fontSize": "{Footnote}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "bold": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Bold}",
            "lineHeight": "{Default}",
            "fontSize": "{Footnote}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        }
      },
      "subheadline": {
        "regular": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Regular}",
            "lineHeight": "{Default}",
            "fontSize": "{Subheadline}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "medium": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Medium}",
            "lineHeight": "{Default}",
            "fontSize": "{Subheadline}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "bold": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Bold}",
            "lineHeight": "{Default}",
            "fontSize": "{Subheadline}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        }
      },
      "body": {
        "regular": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Regular}",
            "lineHeight": "{Default}",
            "fontSize": "{Body}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "medium": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Medium}",
            "lineHeight": "{Default}",
            "fontSize": "{Body}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "bold": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Bold}",
            "lineHeight": "{Default}",
            "fontSize": "{Body}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        }
      },
      "title": {
        "regular": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Regular}",
            "lineHeight": "{Default}",
            "fontSize": "{Title}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "medium": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Medium}",
            "lineHeight": "{Default}",
            "fontSize": "{Title}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "bold": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Bold}",
            "lineHeight": "{Default}",
            "fontSize": "{Title}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        }
      },
      "largetitle": {
        "regular": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Regular}",
            "lineHeight": "{Default}",
            "fontSize": "{LargeTitle}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "medium": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Medium}",
            "lineHeight": "{Default}",
            "fontSize": "{LargeTitle}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        },
        "bold": {
          "value": {
            "fontFamily": "{General Sans}",
            "fontWeight": "{Bold}",
            "lineHeight": "{Default}",
            "fontSize": "{LargeTitle}",
            "letterSpacing": "{0}"
          },
          "type": "typography"
        }
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "source",
      "semantic"
    ]
  }
}
  ```
</details>

<details>
  <summary>Errors while running generator</summary>
 

  ```
Property Reference Errors:
Reference doesn't exist: semantic.button.background.primary.default.value tries to reference brand.500, which is not defined
Reference doesn't exist: semantic.button.background.primary.pressed.value tries to reference brand.600, which is not defined
Reference doesn't exist: semantic.button.background.secondary.default.value tries to reference gray.800, which is not defined
Reference doesn't exist: semantic.button.background.secondary.pressed.value tries to reference gray.900, which is not defined
Reference doesn't exist: semantic.button.background.disabled.default.value tries to reference gray.100, which is not defined
Reference doesn't exist: semantic.button.background.success.default.value tries to reference green.500, which is not defined
Reference doesn't exist: semantic.button.background.success.pressed.value tries to reference green.600, which is not defined
Reference doesn't exist: semantic.button.background.destructive.default.value tries to reference red.500, which is not defined
Reference doesn't exist: semantic.button.background.destructive.pressed.value tries to reference red.600, which is not defined
Reference doesn't exist: semantic.button.background.transparent.default.value tries to reference transparent, which is not defined
Reference doesn't exist: semantic.button.foreground.default.value tries to reference white, which is not defined
Reference doesn't exist: semantic.button.foreground.disabled.value tries to reference gray.200, which is not defined
Reference doesn't exist: semantic.button.foreground.success.value tries to reference green.500, which is not defined
Reference doesn't exist: semantic.button.foreground.destructive.value tries to reference red.500, which is not defined
Reference doesn't exist: semantic.button.foreground.onTransparent.default.value tries to reference gray.900, which is not defined
Reference doesn't exist: semantic.button.foreground.onTransparent.pressed.value tries to reference gray.800, which is not defined
Reference doesn't exist: semantic.background.default.value tries to reference gray.100, which is not defined
Reference doesn't exist: semantic.background.neutral.value tries to reference white, which is not defined
Reference doesn't exist: semantic.default.footnote.regular.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.footnote.regular.value.fontWeight tries to reference Regular, which is not defined
Reference doesn't exist: semantic.default.footnote.regular.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.footnote.regular.value.fontSize tries to reference Footnote, which is not defined
Reference doesn't exist: semantic.default.footnote.regular.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.footnote.medium.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.footnote.medium.value.fontWeight tries to reference Medium, which is not defined
Reference doesn't exist: semantic.default.footnote.medium.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.footnote.medium.value.fontSize tries to reference Footnote, which is not defined
Reference doesn't exist: semantic.default.footnote.medium.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.footnote.bold.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.footnote.bold.value.fontWeight tries to reference Bold, which is not defined
Reference doesn't exist: semantic.default.footnote.bold.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.footnote.bold.value.fontSize tries to reference Footnote, which is not defined
Reference doesn't exist: semantic.default.footnote.bold.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.subheadline.regular.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.subheadline.regular.value.fontWeight tries to reference Regular, which is not defined
Reference doesn't exist: semantic.default.subheadline.regular.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.subheadline.regular.value.fontSize tries to reference Subheadline, which is not defined
Reference doesn't exist: semantic.default.subheadline.regular.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.subheadline.medium.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.subheadline.medium.value.fontWeight tries to reference Medium, which is not defined
Reference doesn't exist: semantic.default.subheadline.medium.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.subheadline.medium.value.fontSize tries to reference Subheadline, which is not defined
Reference doesn't exist: semantic.default.subheadline.medium.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.subheadline.bold.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.subheadline.bold.value.fontWeight tries to reference Bold, which is not defined
Reference doesn't exist: semantic.default.subheadline.bold.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.subheadline.bold.value.fontSize tries to reference Subheadline, which is not defined
Reference doesn't exist: semantic.default.subheadline.bold.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.body.regular.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.body.regular.value.fontWeight tries to reference Regular, which is not defined
Reference doesn't exist: semantic.default.body.regular.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.body.regular.value.fontSize tries to reference Body, which is not defined
Reference doesn't exist: semantic.default.body.regular.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.body.medium.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.body.medium.value.fontWeight tries to reference Medium, which is not defined
Reference doesn't exist: semantic.default.body.medium.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.body.medium.value.fontSize tries to reference Body, which is not defined
Reference doesn't exist: semantic.default.body.medium.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.body.bold.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.body.bold.value.fontWeight tries to reference Bold, which is not defined
Reference doesn't exist: semantic.default.body.bold.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.body.bold.value.fontSize tries to reference Body, which is not defined
Reference doesn't exist: semantic.default.body.bold.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.title.regular.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.title.regular.value.fontWeight tries to reference Regular, which is not defined
Reference doesn't exist: semantic.default.title.regular.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.title.regular.value.fontSize tries to reference Title, which is not defined
Reference doesn't exist: semantic.default.title.regular.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.title.medium.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.title.medium.value.fontWeight tries to reference Medium, which is not defined
Reference doesn't exist: semantic.default.title.medium.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.title.medium.value.fontSize tries to reference Title, which is not defined
Reference doesn't exist: semantic.default.title.medium.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.title.bold.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.title.bold.value.fontWeight tries to reference Bold, which is not defined
Reference doesn't exist: semantic.default.title.bold.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.title.bold.value.fontSize tries to reference Title, which is not defined
Reference doesn't exist: semantic.default.title.bold.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.largetitle.regular.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.largetitle.regular.value.fontWeight tries to reference Regular, which is not defined
Reference doesn't exist: semantic.default.largetitle.regular.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.largetitle.regular.value.fontSize tries to reference LargeTitle, which is not defined
Reference doesn't exist: semantic.default.largetitle.regular.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.largetitle.medium.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.largetitle.medium.value.fontWeight tries to reference Medium, which is not defined
Reference doesn't exist: semantic.default.largetitle.medium.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.largetitle.medium.value.fontSize tries to reference LargeTitle, which is not defined
Reference doesn't exist: semantic.default.largetitle.medium.value.letterSpacing tries to reference 0, which is not defined
Reference doesn't exist: semantic.default.largetitle.bold.value.fontFamily tries to reference General Sans, which is not defined
Reference doesn't exist: semantic.default.largetitle.bold.value.fontWeight tries to reference Bold, which is not defined
Reference doesn't exist: semantic.default.largetitle.bold.value.lineHeight tries to reference Default, which is not defined
Reference doesn't exist: semantic.default.largetitle.bold.value.fontSize tries to reference LargeTitle, which is not defined
Reference doesn't exist: semantic.default.largetitle.bold.value.letterSpacing tries to reference 0, which is not defined


/Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/node_modules/style-dictionary/lib/exportPlatform.js:125
    throw new Error('Problems were found when trying to resolve property references');
    ^

Error: Problems were found when trying to resolve property references
    at Object.exportPlatform (/Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/node_modules/style-dictionary/lib/exportPlatform.js:125:11)
    at Object.buildPlatform (/Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/node_modules/style-dictionary/lib/buildPlatform.js:56:21)
    at /Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/node_modules/style-dictionary/lib/buildAllPlatforms.js:31:10
    at Array.forEach (<anonymous>)
    at Object.buildAllPlatforms (/Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/node_modules/style-dictionary/lib/buildAllPlatforms.js:30:39)
    at Object.<anonymous> (/Users/markmooibroek/.nvm/versions/node/v16.19.1/lib/node_modules/style-dictionary-figma-flutter/build.js:33:25)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
  ```
</details>

Can you perhaps tell me if this is indeed not supported or maybe how I can fix this?

**Comment by mark-nicepants** [comment]
Went a different route and created a parser myself, specifically designed for targetting Flutter. https://pub.dev/packages/figma2flutter
